package mistakes;

public class MistakesGenericsTypeParamaterTypeErasure {

    public static void main(String[] args) {

        /**  1-
         * Parameter Type is defined based on parameters given in Consumer<T> interface so we can use
         * parameter type based on our required as generics
         */
        ConsumerImplementationInteger consumerImplementationInteger= new ConsumerImplementationInteger();
        consumerImplementationInteger.consume(12);

        ConsumerImplementationString consumerImplementationString = new ConsumerImplementationString();
        consumerImplementationString.consume("Arpan");

        /**
         * 2- TypeErasure
         *
         *  As per doc ,TypeErasure means that generic type information is not available to JVM at run time
         *  only for compile time.
         *  Bridge Method generated by the compiler in polymorphism
         *
         *
         */


        /**
         * Q14. Are There Any Situations Where Generic Type Information Is Available at Runtime?
         * There is one situation where a generic type is available at runtime.
         * This is when a generic type is part of the class signature like so:
         *
         * public class CatCage implements Cage<Cat>
         * Copy
         * By using reflection, we get this type parameter:
         */







    }
}
