spring:
  config:
    activate:
      on-profile: "dev"

application:
  name: ARPAN-BAGS-BACKEND

backend:
  message: "Welcome to Backend Section related to dev APIs"


#arpanbagsprivatejaihanuman
#https://emn178.github.io/online-tools/sha256.html
jwt:
  jwtSecretKey : 33d5581a2d443825d32f8d634eeed46d3c21bb6927f61bfe83d1096f381ef7f6
  jwtExpiryTimeout-milliseconds : 2500001


