spring:
  data:
    elasticsearch:
      cluster-name: productService
      cluster-nodes: localhost:9200

server:
  port: 9098

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
