server: 
  port : 9092
  error : 
    include-message: always
  servlet:
    contextPath: /myWebApp

#eureka:
 # client:
#    serviceUrl:
  #    defaultZone: http://localhost:9094/eureka/

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arpanbagsproduct
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: "ARPAN-BAGS-PRODUCTS"

#arpanbagsprivatejaihanuman
#https://emn178.github.io/online-tools/sha256.html
jwt: 
  jwtSecretKey : 33d5581a2d443825d32f8d634eeed46d3c21bb6927f61bfe83d1096f381ef7f6
  jwtExpiryTimeout-milliseconds : 2500001


